# Simple package

name: simple-package 
parent: default

matches:
  - triggers: ["::block", "::mb"]
    replace: "<blockquote>$|$</blockquote>"
      
  - trigger: "::im"
    replace: "![[{{clipboard}}|250]]" 
    vars:
    - name: "clipboard"
      type: "clipboard"

  - triggers: ["::collapse:", "::mcol"]
    replace: "<details><summary>$|$</summary>  \n
        <p>\n
        </p>\n
        </details>\n"

  - triggers: ["::asi", "::aside"]
    replace: "<s class=\"aside-hide\">$|$\n</s>\n"

  - triggers: ["::adm", ":admonition"]
    replace: "```ad-note\n
        title:\n
        $|$\n
        ```\n"
        
  - trigger: "::$nl"
    replace: "\n"
        
  - trigger: "::@e"
    form: "{{description}}"
    form_fields:
     description:
      type: choice
      values: 
        - deon.chan@arrow.com 
        - deon.chan1993@gmail.com 
        - ecsanz.orders@arrow.com 
        - ecsanz.licensingeta@arrow.com
        - ecsanz.renewals@arrow.com
        - ecsanz.omarchiving@arrow.com
        - ecsanz.purchasing@arrow.com
       

